server:
  port: 8093
spring:
  application:
    name: ecommerce-seckill
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
rocketmq:
  name-server: localhost:9876
  producer:
    group: ${spring.application.name}-producer
