server:
  port: 8090
spring:
  application:
    name: ecommerce-file
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
minio:
  endpoint: http://localhost:9000
  access-key: minio
  secret-key: minioadmin
  bucket: ecommerce

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
